title: MedTRACK Support
description: Support and documentation for MedTRACK - Your Simple Medication Tracking App
baseurl: "/medtrack-support" # the subpath of your site
url: "https://sireneast.github.io" # your GitHub Pages URL

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore 